spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: post
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: true
    generate-ddl: true

